### ISSUE TITLE
Paper results reproduction instructions

### ISSUE THREAD

**Issue by alfassy** [yunjiazhang/ReAcTable#1]
Hi,
Thank you for the great work and interesting paper.
I noticed that the README is empty, can you please provide instructions on how to use the code in order to reproduce the paper results? for example to reproduce the results of REACTABLE without voting on WikiTQ as presented in Table 1 of the paper?

Thank you,
Amit

**Comment by yunjiazhang** [comment]
You may refer to newly provided notebook in the folder notebook/. The numbers may not be exactly the same as the codex model have been deprecated. https://platform.openai.com/docs/deprecations/deprecations
